apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bluefin-db
  description: StoresBluefinapplicationDatabase
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  type: database
  owner: team-platform
  system: bluefin