apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fiserv-devops
  description: fiserv-devops
  links:
    - url: http://www.backstage.io/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: FiservDEVOPS
    email: demo@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [it]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-group
  description: Backstage-example-group
spec:
  targets:
    - ./it-dept.yaml
    - ./dev-dept.yaml
    - ./team-bluefin-group.yaml
    - ./team-platform-group.yaml
