apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-bluefin
  description: team-bluefin
spec:
  type: team
  profile:
    displayName: Bluefin-dev
    # Intentional no displayName for testing
    email: team-bluefin@example.com
    picture: https://api.dicebear.com/7.x/bottts/svg?seed=Boots
  parent: development
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: James
spec:
  profile:
    displayName: James
    email: james.higginsthomas@fiserv.com
    picture: https://api.dicebear.com/7.x/personas/svg?seed=Shadow
  memberOf: [team-bluefin]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Jacob
spec:
  profile:
    displayName: Jacob
    email: jacob.vaidyan@fiserv.com
    picture: https://api.dicebear.com/7.x/personas/svg?seed=Gizmo
  memberOf: [team-bluefin]
